"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ScoreBreakdown } from "@/components/ScoreBreakdown";
import { StatusBadge } from "@/components/StatusBadge";
import { duration, timecode } from "@/lib/format";
import { LIBRARY_STATUSES, type ClipWithContext, type LibraryStatus } from "@/lib/types";

interface SearchHit {
  source_video_id: string;
  source_title: string | null;
  headline: string;
  rank: number;
}

export function LibraryBrowser({ initial }: { initial: ClipWithContext[] }) {
  const [clips, setClips] = useState(initial);
  const [filter, setFilter] = useState<LibraryStatus | "all">("all");
  const [query, setQuery] = useState("");
  const [hits, setHits] = useState<SearchHit[] | null>(null);
  const [searching, setSearching] = useState(false);
  const [searchError, setSearchError] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    try {
      const res = await fetch("/api/clips", { cache: "no-store" });
      if (res.ok) setClips(await res.json());
    } catch {
      /* next tick */
    }
  }, []);

  // Debounced transcript search across every source ever ingested.
  useEffect(() => {
    const term = query.trim();
    if (term.length < 2) {
      setHits(null);
      setSearchError(null);
      return;
    }

    setSearching(true);
    const timer = setTimeout(async () => {
      try {
        const res = await fetch(`/api/search?q=${encodeURIComponent(term)}`, {
          cache: "no-store",
        });
        const payload = await res.json();
        if (res.ok) {
          setHits(payload);
          setSearchError(null);
        } else {
          setHits(null);
          setSearchError(payload.error ?? "Search failed.");
        }
      } catch {
        setSearchError("Search failed.");
      } finally {
        setSearching(false);
      }
    }, 350);

    return () => clearTimeout(timer);
  }, [query]);

  const counts = useMemo(() => {
    const out: Record<string, number> = { all: clips.length };
    for (const status of LIBRARY_STATUSES) {
      out[status] = clips.filter((c) => c.library_status === status).length;
    }
    return out;
  }, [clips]);

  const visible = useMemo(
    () => (filter === "all" ? clips : clips.filter((c) => c.library_status === filter)),
    [clips, filter],
  );

  async function setLibraryStatus(clipId: string, status: LibraryStatus) {
    const res = await fetch(`/api/clips/${clipId}`, {
      method: "PATCH",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ libraryStatus: status }),
    });
    if (res.ok) {
      const updated = await res.json();
      setClips((cs) => cs.map((c) => (c.id === clipId ? { ...c, ...updated } : c)));
    }
  }

  return (
    <div className="space-y-6">
      {/* Search across every transcript. */}
      <div className="panel p-5">
        <label htmlFor="q" className="eyebrow">
          Search everything anyone said
        </label>
        <input
          id="q"
          type="search"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder='e.g. going to school   or   "what are you doing"'
          className="panel-inset mt-3 w-full px-4 py-3 text-sm outline-none placeholder:text-dim"
          style={{ background: "var(--panel-2)" }}
        />

        {searching && <p className="eyebrow mt-3">searching…</p>}

        {searchError && (
          <p className="mt-3 text-xs" style={{ color: "var(--peak)" }} role="alert">
            {searchError}
          </p>
        )}

        {hits && !searching && (
          <div className="mt-4">
            {hits.length === 0 ? (
              <p className="text-sm text-dim">
                Nothing matched. Only sources that finished transcribing are
                searchable.
              </p>
            ) : (
              <ul className="space-y-3">
                {hits.map((hit) => (
                  <li key={hit.source_video_id} className="panel-inset p-3">
                    <p className="text-xs font-medium">
                      {hit.source_title ?? "Untitled source"}
                    </p>
                    {/* ts_headline returns <b> around the match; render it, but
                        it is generated by Postgres from our own column, not by
                        the user. */}
                    <p
                      className="mt-1 text-xs leading-relaxed text-dim [&_b]:text-[color:var(--lamp)]"
                      dangerouslySetInnerHTML={{ __html: hit.headline }}
                    />
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}
      </div>

      {/* Library status filters. */}
      <div className="flex flex-wrap gap-1.5">
        {(["all", ...LIBRARY_STATUSES] as const).map((status) => {
          const active = filter === status;
          const count = counts[status] ?? 0;
          return (
            <button
              key={status}
              type="button"
              onClick={() => setFilter(status)}
              className="rounded-[3px] border px-3 py-1.5 text-xs transition-colors"
              style={{
                borderColor: active ? "var(--lamp)" : "var(--rule)",
                color: active ? "var(--lamp)" : "var(--dim)",
                background: active ? "rgba(240,169,59,.08)" : "transparent",
              }}
            >
              {status}
              <span className="tc ml-2 opacity-60">{count}</span>
            </button>
          );
        })}
      </div>

      {visible.length === 0 ? (
        <div className="panel px-6 py-16 text-center">
          <p className="text-sm text-dim">
            {filter === "all"
              ? "No clips yet. Add a source video to get started."
              : `Nothing in ${filter}.`}
          </p>
        </div>
      ) : (
        <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">
          {visible.map((clip) => (
            <article key={clip.id} className="panel flex flex-col p-4">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium">
                    {clip.title ?? clip.source?.title ?? "Untitled clip"}
                  </p>
                  <p className="tc mt-1 text-[11px] text-dim">
                    {timecode(clip.start_seconds)} → {timecode(clip.end_seconds)} ·{" "}
                    {duration(clip.end_seconds - clip.start_seconds)}
                  </p>
                </div>
                <StatusBadge status={clip.status} />
              </div>

              <div className="mt-4">
                <ScoreBreakdown
                  score={clip.score}
                  factors={clip.score_factors}
                  rationale={clip.rationale}
                  category={clip.category}
                  rank={clip.rank}
                  compact
                />
              </div>

              <div className="mt-4 flex flex-wrap gap-1.5 border-t border-rule pt-3">
                {LIBRARY_STATUSES.filter((s) => s !== clip.library_status).map((status) => (
                  <button
                    key={status}
                    type="button"
                    onClick={() => setLibraryStatus(clip.id, status)}
                    className="rounded-[2px] border px-2 py-1 text-[10px] text-dim transition-colors hover:text-[color:var(--text)]"
                  >
                    → {status}
                  </button>
                ))}
              </div>
            </article>
          ))}
        </div>
      )}

      <button
        type="button"
        onClick={refresh}
        className="text-xs text-dim underline underline-offset-4"
      >
        Refresh
      </button>
    </div>
  );
}
